### ISSUE TITLE
Oversette ui

### ISSUE THREAD

**Issue by TrymVei** [strombraaten/climatecode#13]
https://starlight.astro.build/guides/i18n/#translate-starlights-ui

**Comment by strombraaten** [comment]
Begynte med det i [denne commiten](https://github.com/strombraaten/climatecode/commit/fc4352801fa667c75fe10625bb29117398c50298) her, @TrymVei

**Comment by strombraaten** [comment]
En ting jeg ikke skjønner riktignok er hvorfor ikke de etikettene her ikke endres i så fall, som et resultat av at jeg har lagd en .JSON-fil

![Simens-skjermbilder-14-10-2024-kl16 09](https://github.com/user-attachments/assets/3827e91d-e32a-40e8-8d9b-c48340845503)

**Comment by TrymVei** [comment]
Sikker på at du husket å pushe json filen? Ser bare at du har lagt til en import men ikke json fila

**Comment by strombraaten** [comment]
> Sikker på at du husket å pushe json filen? Ser bare at du har lagt til en import men ikke json fila

Jepp, [den ligger her](https://github.com/strombraaten/climatecode/blob/main/src/content/i18n/nb-NO.json): src/content/i18n/nb-NO.json

Men den må sikkert nevnes et eller annet sted for at grensesnittet skal vite at den finnes. Lager en PR på det jeg, så ser jeg hva jeg får til

**Comment by strombraaten** [comment]
#14

**Comment by TrymVei** [comment]
```export const collections = {
  docs: defineCollection({ schema: docsSchema() }),
  i18n: defineCollection({ type: 'data', schema: i18nSchema() }), <----- DENNE
};
```

Har vel ikke lagt til den linjen her?

**Comment by strombraaten** [comment]
Joda, den ligger i `config.ts`

**Comment by strombraaten** [comment]
I så fall så kan vel egentlig den her lukkes, kan den ikke det?

**Comment by TrymVei** [comment]
Yes! Denne er vel løst nå

**Comment by strombraaten** [comment]
Hurra!
